version: "3.7"

services:
  flask:
    build: 
      context: ./flask
      args:
        - APP_NAME=My_Flask_App  # Pass build argument to Dockerfile
    container_name: flask
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    expose:
      - 8080
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "8084:80"
